name: CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-and-lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest flake8 black
    
    - name: Lint with flake8
      run: |
        flake8 main.py --max-line-length=120 --ignore=E501,W503
      continue-on-error: true
    
    - name: Format check with black
      run: |
        black --check main.py
      continue-on-error: true
    
    - name: Run tests
      run: |
        pytest tests/ -v
      continue-on-error: true

  build-docker:
    runs-on: ubuntu-latest
    needs: test-and-lint
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Build Docker image
      run: |
        docker build -t oneplus-price-predictor:latest .
    
    - name: Test Docker container
      run: |
        docker run -d -p 8000:8000 --name test-container oneplus-price-predictor:latest
        sleep 10
        curl http://localhost:8000/ || exit 1
        docker stop test-container
        docker rm test-container